//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var idIOT = require('./idIOT');
var idIOTClient = idIOT.Client;
var idIOTProcessor = idIOT.Processor;
var ttypes = require('./tutorial_types');
//HELPER FUNCTIONS AND STRUCTURES

var idIOT_runnable_scheduleRun_args = function(args) {
  this.id = null;
  this.timestamp = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.timestamp !== undefined && args.timestamp !== null) {
      this.timestamp = args.timestamp;
    }
  }
};
idIOT_runnable_scheduleRun_args.prototype = {};
idIOT_runnable_scheduleRun_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.timestamp = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

idIOT_runnable_scheduleRun_args.prototype.write = function(output) {
  output.writeStructBegin('idIOT_runnable_scheduleRun_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.timestamp !== null && this.timestamp !== undefined) {
    output.writeFieldBegin('timestamp', Thrift.Type.I64, 2);
    output.writeI64(this.timestamp);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var idIOT_runnable_scheduleRun_result = function(args) {
  this.success = null;
  this.pastTimeEx = null;
  if (args instanceof ttypes.EventInPastException) {
    this.pastTimeEx = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.pastTimeEx !== undefined && args.pastTimeEx !== null) {
      this.pastTimeEx = args.pastTimeEx;
    }
  }
};
idIOT_runnable_scheduleRun_result.prototype = {};
idIOT_runnable_scheduleRun_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.I32) {
        this.success = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.pastTimeEx = new ttypes.EventInPastException();
        this.pastTimeEx.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

idIOT_runnable_scheduleRun_result.prototype.write = function(output) {
  output.writeStructBegin('idIOT_runnable_scheduleRun_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I32, 0);
    output.writeI32(this.success);
    output.writeFieldEnd();
  }
  if (this.pastTimeEx !== null && this.pastTimeEx !== undefined) {
    output.writeFieldBegin('pastTimeEx', Thrift.Type.STRUCT, 1);
    this.pastTimeEx.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var idIOT_runnable_runNow_args = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
  }
};
idIOT_runnable_runNow_args.prototype = {};
idIOT_runnable_runNow_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

idIOT_runnable_runNow_args.prototype.write = function(output) {
  output.writeStructBegin('idIOT_runnable_runNow_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var idIOT_runnable_runNow_result = function(args) {
  this.success = null;
  this.deviceBrokeEx = null;
  if (args instanceof ttypes.Exception) {
    this.deviceBrokeEx = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.deviceBrokeEx !== undefined && args.deviceBrokeEx !== null) {
      this.deviceBrokeEx = args.deviceBrokeEx;
    }
  }
};
idIOT_runnable_runNow_result.prototype = {};
idIOT_runnable_runNow_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.deviceBrokeEx = new ttypes.Exception();
        this.deviceBrokeEx.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

idIOT_runnable_runNow_result.prototype.write = function(output) {
  output.writeStructBegin('idIOT_runnable_runNow_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.deviceBrokeEx !== null && this.deviceBrokeEx !== undefined) {
    output.writeFieldBegin('deviceBrokeEx', Thrift.Type.STRUCT, 1);
    this.deviceBrokeEx.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var idIOT_runnableClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
Thrift.inherits(idIOT_runnableClient, idIOTClient);
idIOT_runnableClient.prototype.seqid = function() { return this._seqid; };
idIOT_runnableClient.prototype.new_seqid = function() { return this._seqid += 1; };

idIOT_runnableClient.prototype.scheduleRun = function(id, timestamp, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_scheduleRun(id, timestamp);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_scheduleRun(id, timestamp);
  }
};

idIOT_runnableClient.prototype.send_scheduleRun = function(id, timestamp) {
  var output = new this.pClass(this.output);
  var params = {
    id: id,
    timestamp: timestamp
  };
  var args = new idIOT_runnable_scheduleRun_args(params);
  try {
    output.writeMessageBegin('scheduleRun', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

idIOT_runnableClient.prototype.recv_scheduleRun = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new idIOT_runnable_scheduleRun_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.pastTimeEx) {
    return callback(result.pastTimeEx);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('scheduleRun failed: unknown result');
};

idIOT_runnableClient.prototype.runNow = function(id, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_runNow(id);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_runNow(id);
  }
};

idIOT_runnableClient.prototype.send_runNow = function(id) {
  var output = new this.pClass(this.output);
  var params = {
    id: id
  };
  var args = new idIOT_runnable_runNow_args(params);
  try {
    output.writeMessageBegin('runNow', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

idIOT_runnableClient.prototype.recv_runNow = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new idIOT_runnable_runNow_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.deviceBrokeEx) {
    return callback(result.deviceBrokeEx);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('runNow failed: unknown result');
};
var idIOT_runnableProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
Thrift.inherits(idIOT_runnableProcessor, idIOTProcessor);
idIOT_runnableProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
idIOT_runnableProcessor.prototype.process_scheduleRun = function(seqid, input, output) {
  var args = new idIOT_runnable_scheduleRun_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.scheduleRun.length === 2) {
    Q.fcall(this._handler.scheduleRun.bind(this._handler),
      args.id,
      args.timestamp
    ).then(function(result) {
      var result_obj = new idIOT_runnable_scheduleRun_result({success: result});
      output.writeMessageBegin("scheduleRun", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      if (err instanceof ttypes.EventInPastException) {
        result = new idIOT_runnable_scheduleRun_result(err);
        output.writeMessageBegin("scheduleRun", Thrift.MessageType.REPLY, seqid);
      } else {
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("scheduleRun", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.scheduleRun(args.id, args.timestamp, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.EventInPastException) {
        result_obj = new idIOT_runnable_scheduleRun_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("scheduleRun", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("scheduleRun", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
idIOT_runnableProcessor.prototype.process_runNow = function(seqid, input, output) {
  var args = new idIOT_runnable_runNow_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.runNow.length === 1) {
    Q.fcall(this._handler.runNow.bind(this._handler),
      args.id
    ).then(function(result) {
      var result_obj = new idIOT_runnable_runNow_result({success: result});
      output.writeMessageBegin("runNow", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      if (err instanceof ttypes.Exception) {
        result = new idIOT_runnable_runNow_result(err);
        output.writeMessageBegin("runNow", Thrift.MessageType.REPLY, seqid);
      } else {
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("runNow", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.runNow(args.id, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.Exception) {
        result_obj = new idIOT_runnable_runNow_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("runNow", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("runNow", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
